# longview-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: longview-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: longview
  template:
    metadata:
      labels:
        app: longview
    spec:
      containers:
        - name: longview
          image: your-dockerhub-username/longview-app:latest
          ports:
            - containerPort: 80
Transform: AWS::Serverless-2016-10-31
Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties: {}