# mailing-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailing-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mailing
  template:
    metadata:
      labels:
        app: mailing
    spec:
      containers:
      - name: mailing
        image: your-dockerhub-username/mailing-app:latest
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "mssql"
        - name: DB_PORT
          value: "1433"
        - name: DB_USER
          value: "sa"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-secret
              key: MSSQL_SA_PASSWORD
