# oesys-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oesys-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oesys
  template:
    metadata:
      labels:
        app: oesys
    spec:
      containers:
      - name: oesys
        image: your-dockerhub-username/oesys-app:latest
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
